name: GitHub Actions Demo
on:
  pull_request:
    branches:
      - main
    types: [closed]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to update gist
    steps:
    - uses: actions/checkout@v2
    - name: Update gist sample code
      id: hello
      uses: phongnm-dev/action-kuc-demo@1.0.8
      with:
        doc-folder: 'docs'
        gist-username: 'phongnm-dev'
        gist-token: ${{ secrets.GISTTOKEN }}
